USE go-test;

CREATE TABLE `myasset` (
    `Aid` INT(10) NOT NULL AUTO_INCREMENT,
    `Uid` INT(10) NOT NULL,
    `AssetType` VARCHAR(64) NULL DEFAULT NULL,
    `AssetSubType` VARCHAR(64) NULL DEFAULT NULL,
    `Code` VARCHAR(64) NULL DEFAULT NULL,
    `Amount` FLOAT NULL DEFAULT NULL,
    `Label` VARCHAR(64) NULL DEFAULT NULL,
    `Market` VARCHAR(64) NULL DEFAULT NULL,
    PRIMARY KEY (`Aid`)
);

CREATE TABLE `user` (
    `Uid` INT(10) NOT NULL AUTO_INCREMENT,
    `Email` VARCHAR(64) NOT NULL UNIQUE,
    `Name` VARCHAR(64) NOT NULL,
    `Gender` VARCHAR(64) NULL DEFAULT NULL,
    `Picture` VARCHAR(256) NULL DEFAULT NULL,
    `LineId` VARCHAR(64) NULL DEFAULT NULL,
    PRIMARY KEY (`Uid`)
);

