USE go-test;

CREATE TABLE `myasset` (
    `Aid` INT(10) NOT NULL AUTO_INCREMENT,
    `AssetType` VARCHAR(64) NULL DEFAULT NULL,
    `AssetSubType` VARCHAR(64) NULL DEFAULT NULL,
    `Code` VARCHAR(64) NULL DEFAULT NULL,
    `Amount` FLOAT NULL DEFAULT NULL,
    `Label` VARCHAR(64) NULL DEFAULT NULL,
    `Market` VARCHAR(64) NULL DEFAULT NULL,
    PRIMARY KEY (`Aid`)
);

